# INFORMACIÓN GENERAL DE LA APLICACIÓN
spring.application.name=auth


# DATASOURCE ORACLE AUTONOMOUS
spring.datasource.url=jdbc:oracle:thin:@db01_high?TNS_ADMIN=C:/Wallet_DB01/
spring.datasource.username=AUTH_SERVICE
spring.datasource.password=DuocUc..2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURACIÓN DE SEGURIDAD - PASSWORD
security.password.min-length=8
security.password.max-length=64
security.password.require-uppercase=true
security.password.require-lowercase=true
security.password.require-digit=true
security.password.require-special=true
